# #############################
# Keyboard Shortcuts
# #############################

# General
unbind = SUPER, P
unbind = SUPER, L
unbind = SUPER, h
unbind = SUPER, l
unbind = SUPER, k
unbind = SUPER, j
unbind = SUPER_SHIFT, h
unbind = SUPER_SHIFT, l
unbind = SUPER_SHIFT, k
unbind = SUPER_SHIFT, j

# Window Navigation
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d
bind = SUPER+SHIFT, h, movewindow, l
bind = SUPER+SHIFT, l, movewindow, r
bind = SUPER+SHIFT, k, movewindow, u
bind = SUPER+SHIFT, j, movewindow, d

# File Manager

# IDE
unbind = SUPER, C

# Browser
unbind = SUPER, W
bind = SUPER, W, exec, brave

# Terminal
unbind = SUPER, T
bind = SUPER, T, exec, kitty


# #############################
# Special Workspaces
# #############################

# System Monitor
bind = SUPER, P, exec, caelestia toggle sysmon


# #############################
# Hardware
# #############################

# Monitors
monitor = HDMI-A-1, 1920x1080@75, -1920x0, 1
monitor = DP-1, 2560x1440@165, 0x0, 1

workspace = 1, monitor:DP-1, default:true, persistent:true
workspace = 11, monitor:HDMI-A-1, default:true, persistent:true
workspace = r[2-10], monitor:DP-1, persistent:true
workspace = r[12-20], monitor:HDMI-A-1, persistent:true
